
development:
  adapter: postgresql
  encoding: unicode
  database: alquiler_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: alquiler_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: alquiler_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
